Fixed stateful provisioning UEFI boot settings for aarch64
warewulf/warewulf3 pull request #199
Opened 2019-09-04 02:18 UTC by NaohiroTamura

This patch fixed stateful provisioning UEFI boot settings for aarch64
so as not to call grub2-install by checking the existance of
/boot/efi/EFI/*/grubaa64.efi in the same way as grubx64.efi for
x86_64.

Without this fix, wrong grub boot entry is created and the boot from
local disk fails.

This problem was originally reported from OpenHPC 1.3.8 CentOS 7.6
aarch64 user.

2019-09-04 15:26 UTC, bensallen approved these changes
Looks good. Thanks for the fix!

2019-09-04 15:27 UTC, bensallen requested changes
@NaohiroTamura Can you please change this PR to target the development branch instead of master?

2019-09-05 00:43 UTC, NaohiroTamura commented
@bensallen thanks for the review.

2019-10-04 19:00 UTC, bensallen approved these changes

2019-10-04 19:00 UTC, merged