Add support for dhcp shared networks
warewulf/warewulf3 pull request #238
Opened 2020-04-17 16:20 UTC by redsox38

Rebase #263 against upstream development branch

Our use case is that each rack in our cluster is a separate /26 using dhcp helper to forward requests to an off cluster ohpc management node. The purpose of the network cuts is to facilitate a smoother transition to ohpc 2.0 when it becomes available that doesn't require taking the entire cluster offline at once. The patch is based on this thread https://groups.google.com/a/lbl.gov/forum/#!topic/warewulf/Yx9OMqkyJKU and it adds a configuration directive "dhcp network = shared" to enable the behavior, otherwise it reverts to the default behavior.

2020-04-17 19:48 UTC, jmstover commented
Can you add an example `dhcp network` entry to `provision/etc/provision.conf`? Along with what you think the values should be?

If I'm reading it right, it looks like that should be set to `flat` if you want to keep current behavior. In which case, I would liek that to be the default...

2020-04-17 22:42 UTC, jmstover submitted a review, later dismissed
Tentatively looks good. @bensallen ... I'll await your comments on it though. ;)

2020-04-21 03:52 UTC, bensallen requested changes
Can we change the option values from `flat` and `shared` to perhaps `direct` and `relay`. Currently reading the config file I wouldn't actually know what this setting does.

We can describe the two options in the config file as:

Direct - Only generate DHCP host reservations for nodes within the same subnet as the configured 'network device' or 'ip address' (default)
Relay - Generate DHCP host reservations for all nodes in the Warewulf database without regard to subnet. Useful for DHCP relay configurations.

The code changes look fine otherwise.

2020-04-21 13:37 UTC, bensallen approved these changes
Looks good thanks!

2020-04-21 13:38 UTC, merged